name: Nuget

on:
  push:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Push to NuGet
      run: |
        pwsh ./publish.ps1 -key "${{ secrets.NUGET_API_KEY }}"
